### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#48]
Error while following the procedure to build the HTML documentation.

` pip install -r requirements.txt`

```
root@webserver-dev1:~/polycube/Documentation# pip install -r requirements.txt
Collecting Sphinx>=1.8.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0e/5c/e7d076cf2900b38cba5c7d48545953540d86634d391b702067c00d99cb01/Sphinx-1.8.3-py2.py3-none-any.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 320kB/s
Collecting sphinx-rtd-theme==0.4.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ef/0c/e4a462190506bc4bff6ca8cf93da07b2d13e540466d2e8a760352d0c69b0/sphinx_rtd_theme-0.4.2-py2.py3-none-any.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 152kB/s
Collecting sphinxcontrib-spelling>4.0.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/74/22/3fc121b8a7acd4952e0a280ced4703ed0082ae61533204731ef4cdfa01cb/sphinxcontrib-spelling-4.2.0.tar.gz
Collecting sphinxcontrib-websupport (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/52/69/3c2fbdc3702358c5b34ee25e387b24838597ef099761fc9a42c166796e8f/sphinxcontrib_websupport-1.1.0-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl (8.1MB)
    100% |████████████████████████████████| 8.1MB 126kB/s
Collecting imagesize (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from Sphinx>=1.8.1->-r requirements.txt (line 1))
Collecting packaging (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/89/d1/92e6df2e503a69df9faab187c684585f0136662c12bb1f36901d426f3fab/packaging-18.0-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
    100% |████████████████████████████████| 849kB 1.1MB/s
Collecting requests>=2.0.0 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 8.4MB/s
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/dist-packages (from Sphinx>=1.8.1->-r requirements.txt (line 1))
Collecting docutils>=0.11 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 2.0MB/s
Collecting typing; python_version < "3.5" (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Collecting alabaster<0.8,>=0.7 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 6.4MB/s
Collecting snowballstemmer>=1.1 (from Sphinx>=1.8.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 7.2MB/s
Collecting PyEnchant>=1.6.5 (from sphinxcontrib-spelling>4.0.0->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9e/54/04d88a59efa33fefb88133ceb638cdf754319030c28aadc5a379d82140ed/pyenchant-2.0.0.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 6.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i3UU4e/PyEnchant/setup.py", line 212, in <module>
        import enchant
      File "enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i3UU4e/PyEnchant/
```

**Comment by acloudiator** [comment]
`sudo apt-get install python-enchant` solved the above issue. Will have to verify, if this happens again.

**Comment by acloudiator** [comment]
Issue resolved and inactive over 90 days.
